name: Generate Release

env:
  # Used to access private repos
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version number in the following format: major.minor.patch"
        required: true

jobs:
  create_release_branch_pr:
    name: Create new release branch and PR.
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch from development
        uses: actions/checkout@v2
        with:
          ref: main
         
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: Releases/${{ github.event.inputs.version }}
          title: "Merge release branch ${{ github.event.inputs.version }} into master."

