name: Generate Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version number in the following format: major.minor.patch"
        required: true

jobs:
  create_release_branch_pr:
    name: Create new release branch and PR.
    runs-on: ubuntu-latest
    steps:
      - name: Strip version number
        run: echo "RELEASE_BRANCH=$(echo Releases/${{ github.event.inputs.version }} | sed -e 's:\.:_:g')" >> $GITHUB_ENV

      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          ref: development
      - name: Create release branch from development
        run: |
          git checkout -b ${RELEASE_BRANCH}
          git push origin ${RELEASE_BRANCH}
         
      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${RELEASE_BRANCH}
          title: "Merge release branch ${{ github.event.inputs.version }} into master."

