name: Generate Release

env:
  # Used to access private repos
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version number in the following format: major.minor.patch"
        required: true

jobs:
  create_release_branch_pr:
    name: Create new release branch and PR.
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch from development
        uses: actions/checkout@v2
        with:
          ref: development
        run: |
          git checkout -b Releases/${{ github.event.inputs.version }}
          git push origin Releases/${{ github.event.inputs.version }}
         
      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          base: main
          head: Releases/${{ github.event.inputs.version }}
          title: "Merge release branch ${{ github.event.inputs.version }} into master."

