name: Sample Workflow

on:
  workflow_dispatch:
    inputs:
      skipSubmission:
        description: 'Skip App Store Submission'     
        required: true
        default: "true"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v4.8

    - name: Run script
      run: |
        ./scripts/sample.sh '${{ steps.branch-name.outputs.current_branch }}' '${{ github.event.inputs.skipSubmission }}'
